// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserAndUnitManagement.Infrastructure.Persistence;

#nullable disable

namespace UserAndUnitManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251108200442_ModelChanges")]
    partial class ModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserAndUnitManagement.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcde1"),
                            Breed = "Golden Retriever",
                            Name = "Buddy",
                            PhotoUrl = "",
                            RegistrationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Species = "Dog",
                            UserId = new Guid("d4e5f6a1-b2c3-0987-5432-10fedcba9876")
                        },
                        new
                        {
                            Id = new Guid("fedcba09-8765-4321-0987-654321fedcb1"),
                            Breed = "Siamese",
                            Name = "Whiskers",
                            PhotoUrl = "",
                            RegistrationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Species = "Cat",
                            UserId = new Guid("d4e5f6a1-b2c3-0987-5432-10fedcba9876")
                        });
                });

            modelBuilder.Entity("UserAndUnitManagement.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcde0"),
                            Address = "123 Main St",
                            City = "Anytown",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Unit 101",
                            State = "CA",
                            Status = 0,
                            ZipCode = "12345"
                        },
                        new
                        {
                            Id = new Guid("fedcba09-8765-4321-0987-654321fedcb0"),
                            Address = "456 Oak Ave",
                            City = "Someville",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Unit 202",
                            State = "NY",
                            Status = 0,
                            ZipCode = "54321"
                        });
                });

            modelBuilder.Entity("UserAndUnitManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OptInToDirectory")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowEmailInDirectory")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcdef"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "superadmin@example.com",
                            FirstName = "Super",
                            IsActive = true,
                            LastName = "Admin",
                            OptInToDirectory = true,
                            PasswordHash = "7f2d81eb026f9debd54b30640d8a3c1919e2668294fbb0cbb5e4eccb4c761113",
                            Role = 0,
                            Salt = "af72b314-4a9d-4ea3-9bd6-5d5a55e0ce0b",
                            ShowEmailInDirectory = true
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a1-0987-5432-10fedcba9876"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "propertymanager@example.com",
                            FirstName = "Property",
                            IsActive = true,
                            LastName = "Manager",
                            OptInToDirectory = true,
                            PasswordHash = "4f62a04a1f7c705d4471ac2a93a2c3affcfe5b4846d67e97d723ae2ed898e69b",
                            Role = 1,
                            Salt = "7dda33b8-34f3-4f79-b6c2-73f726b91cb5",
                            ShowEmailInDirectory = true
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a1b2-7890-1234-567890abcdef"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "securityguard@example.com",
                            FirstName = "Security",
                            IsActive = true,
                            LastName = "Guard",
                            OptInToDirectory = true,
                            PasswordHash = "e35ec334b374a96bfede2e97d534429ad44d0eac691d36ff2c1004313e5f2ce3",
                            Role = 2,
                            Salt = "1c64f8b2-fd5c-47d1-bcd5-969b4fe7f819",
                            ShowEmailInDirectory = true
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a1-b2c3-0987-5432-10fedcba9876"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "owner@example.com",
                            FirstName = "Owner",
                            IsActive = true,
                            LastName = "User",
                            OptInToDirectory = true,
                            PasswordHash = "f521e197e6b9c1eea7f68c63c7d334e04e124a4443f162adbe0821e8ec86df0f",
                            Role = 3,
                            Salt = "11d07415-1328-4a81-9605-a70fe8332a22",
                            ShowEmailInDirectory = true
                        },
                        new
                        {
                            Id = new Guid("e5f6a1b2-c3d4-7890-1234-567890abcdef"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tenant@example.com",
                            FirstName = "Tenant",
                            IsActive = true,
                            LastName = "User",
                            OptInToDirectory = true,
                            PasswordHash = "1b45afdfbddbc1196bf03c98af409829a168c5e376e418832e1ac495702d2307",
                            Role = 4,
                            Salt = "cc4f60ed-23d8-45b6-89bd-6ac9be3c828d",
                            ShowEmailInDirectory = true
                        });
                });

            modelBuilder.Entity("UserAndUnitManagement.Domain.Entities.UserUnit", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UnassignedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "UnitId");

                    b.HasIndex("UnitId");

                    b.ToTable("UserUnits");
                });

            modelBuilder.Entity("UserAndUnitManagement.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcde2"),
                            Color = "Silver",
                            Make = "Toyota",
                            Model = "Camry",
                            PlateNumber = "123-ABC",
                            RegistrationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("e5f6a1b2-c3d4-7890-1234-567890abcdef"),
                            Year = 0
                        },
                        new
                        {
                            Id = new Guid("fedcba09-8765-4321-0987-654321fedcb2"),
                            Color = "Black",
                            Make = "Honda",
                            Model = "Civic",
                            PlateNumber = "456-DEF",
                            RegistrationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("e5f6a1b2-c3d4-7890-1234-567890abcdef"),
                            Year = 0
                        });
                });

            modelBuilder.Entity("UserAndUnitManagement.Domain.Entities.Pet", b =>
                {
                    b.HasOne("UserAndUnitManagement.Domain.Entities.User", "User")
                        .WithMany("Pets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserAndUnitManagement.Domain.Entities.UserUnit", b =>
                {
                    b.HasOne("UserAndUnitManagement.Domain.Entities.Unit", "Unit")
                        .WithMany("UserUnits")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserAndUnitManagement.Domain.Entities.User", "User")
                        .WithMany("UserUnits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserAndUnitManagement.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("UserAndUnitManagement.Domain.Entities.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserAndUnitManagement.Domain.Entities.Unit", b =>
                {
                    b.Navigation("UserUnits");
                });

            modelBuilder.Entity("UserAndUnitManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("Pets");

                    b.Navigation("UserUnits");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
